name: ccache
version: '0.2.2'
version-script: |
    git describe --tags

summary: ccache is ccache with cloud storage
description: |
    ccache is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS)
    API, or Redis.

grade: stable
confinement: classic

apps:
    ccache:
        command: bin/ccache.wrapper

    ccache-server:
        environment:
            CCACHE_START_SERVER: 1
            CCACHE_NO_DAEMON: 1
            CCACHE_IDLE_TIMEOUT: 0
        command: bin/ccache.wrapper
        daemon: simple

parts:
    ccache:
        plugin: rust
        source: .
        source-type: git
        build-packages:
        - libssl-dev
        - make
        - pkg-config
        rust-features:
        - gcs
        - redis
        - s3

    wrapper:
        plugin: dump
        source: snap
        prime: [bin]
